### ISSUE TITLE
TypeError: nextCreate is not a function

### ISSUE THREAD

**Issue by jbharrell** [shallinta/material-ui-tree#16]
I'm seeing the following stacktrace when trying to run the sample code.  I've even exported the codesandbox example locally and still get the same.  Maybe you know what I'm doing wrong or maybe there is an issue somewhere:

```
TypeError: nextCreate is not a function
react-dom.development.js:13964
    at mountMemo (/Users/jason.harrell/dev/git/GitHub/aem-dialog-viewer-dev/node_modules/react-dom/cjs/react-dom.development.js:13964:1)
    at Object.useMemo (/Users/jason.harrell/dev/git/GitHub/aem-dialog-viewer-dev/node_modules/react-dom/cjs/react-dom.development.js:14185:1)
    at useMemo (/Users/jason.harrell/dev/git/GitHub/aem-dialog-viewer-dev/node_modules/react/cjs/react.development.js:1525:1)
at renderWithHooks (/Users/jason.harrell/dev/git/GitHub/aem-dialog-viewer-dev/node_modules/react-dom/cjs/react-dom.development.js:13449:1)
    at mountIndeterminateComponent (/Users/jason.harrell/dev/git/GitHub/aem-dialog-viewer-dev/node_modules/react-dom/cjs/react-dom.development.js:15605:1)
    at beginWork (/Users/jason.harrell/dev/git/GitHub/aem-dialog-viewer-dev/node_modules/react-dom/cjs/react-dom.development.js:16238:1)
    at performUnitOfWork (/Users/jason.harrell/dev/git/GitHub/aem-dialog-viewer-dev/node_modules/react-dom/cjs/react-dom.development.js:20279:1)
    at workLoop (/Users/jason.harrell/dev/git/GitHub/aem-dialog-viewer-dev/node_modules/react-dom/cjs/react-dom.development.js:20320:1)
    at renderRoot (/Users/jason.harrell/dev/git/GitHub/aem-dialog-viewer-dev/node_modules/react-dom/cjs/react-dom.development.js:20400:1)
    at performWorkOnRoot (/Users/jason.harrell/dev/git/GitHub/aem-dialog-viewer-dev/node_modules/react-dom/cjs/react-dom.development.js:21357:1)
    at performWork (/Users/jason.harrell/dev/git/GitHub/aem-dialog-viewer-dev/node_modules/react-dom/cjs/react-dom.development.js:21267:1)
    at performSyncWork (/Users/jason.harrell/dev/git/GitHub/aem-dialog-viewer-dev/node_modules/react-dom/cjs/react-dom.development.js:21241:1)
    at requestWork (/Users/jason.harrell/dev/git/GitHub/aem-dialog-viewer-dev/node_modules/react-dom/cjs/react-dom.development.js:21096:1)
    at scheduleWork (/Users/jason.harrell/dev/git/GitHub/aem-dialog-viewer-dev/node_modules/react-dom/cjs/react-dom.development.js:20909:1)
    at dispatchAction (/Users/jason.harrell/dev/git/GitHub/aem-dialog-viewer-dev/node_modules/react-dom/cjs/react-dom.development.js:14118:1)
    at /Users/jason.harrell/dev/git/GitHub/aem-dialog-viewer-dev/node_modules/material-ui-tree/lib/index.es.js:260:1
    at /Users/jason.harrell/dev/git/GitHub/aem-dialog-viewer-dev/src/App.js:153:1
```

**Comment by shallinta** [comment]
https://codesandbox.io/s/94wyyw992r

Is this error found in this above page?  But It works fine in my browser.

I searched this error on google and stack-overflow, no similar results found.

Function `nextCreate` is in react hook `useMemo`, try to check about your react and react-dom version? or even node version?

**Comment by jbharrell** [comment]
@shallinta thanks for responding!  It does not happen on that page, but if I do 'File -> Export as Zip' then unzip it locally.  Run `npm install && npm start` it launches the application.  But then on the first click to expand the tree I get that error.

**Comment by shallinta** [comment]
I got this error when I do what you said. I will see into this later on. Thank you for your attempt.

**Comment by mpalmerlee** [comment]
I'm getting the same issue using this library in my own project. I'm passing all the data available to the Tree component like this:
`<Tree data={rootNode} labelKey="name" valueKey="id" childrenKey="children" />`

**Comment by nuzz78** [comment]
I to am seeing this. I've just upgraded to the latest react, react-dom and material-ui, and so obviously have to upgrade material-ui-tree as well.

versions:
    "@material-ui/core": "^4.0.0-rc.0",
    "@material-ui/icons": "^4.2.1",
    "@material-ui/styles": "^4.2.0",
    "material-ui-tree": "^2.0.1",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-router": "^5.0.1",
    "react-router-dom": "^5.0.1",
    "react-scripts": "^3.0.1",
    "source-map-explorer": "^2.0.1"

I've done some exploring, and have isolated the call thats causing the above error for me. I have some custom stuff I'm doing to populate the tree. It all worked fine under the previous version. At the end of:

`const requestTreeLeafChildrenData = useCallback(
    (leafData, path, toggleFoldStatus) => {
.....
     const data = Object.assign({}, state.data);
     console.log(getNodeDataByPath(data, path, "children"));
     console.log(children);
     getNodeDataByPath(data, path, "children").children = children;
     setState({ data });
     toggleFoldStatus();
`

Now I originally thought that this was caused by not using useCallback, and instead using a react class. However I completely reimplemented using useCallback and I still get the same result.

Now just to be clear, the initial tree is rendering fine, I have my root element. Its when I click on it, and requestTreeLeafChildrenData is called. Its all fine up to the "setState" call. When I check what the children are that are added, it all looks fine.

What I find very curious, is, seeing that this function uses "useCallback", why am I seeing "useMemo" in the stacktrace? my understanding of hooks, is that useMemo is when you have a expensive function, and should only be called at creation? I don't believe we should be seeing "useMemo". Please correct me if I'm wrong.....

**Comment by nuzz78** [comment]
Further to this, I just took your example code, verbatim, and added it as it own class, and then set a route to it, as I'm using the router, and bang, same error. Looks like it might be router related:

```
<useMemo> component:
    in useMemo (created by r)
    in div (created by Transition)
    in div (created by Transition)
    in div (created by Transition)
    in Transition (created by ForwardRef(Collapse))
    in ForwardRef(Collapse) (created by WithStyles(ForwardRef(Collapse)))
    in WithStyles(ForwardRef(Collapse)) (created by r)
    in r (created by L)
    in div (created by ForwardRef(List))
    in ForwardRef(List) (created by WithStyles(ForwardRef(List)))
    in WithStyles(ForwardRef(List)) (created by L)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by L)
    in L (at Test2.js:174)
    in ThemeProvider (at Test2.js:167)
    in Test2 (created by Context.Consumer)
    in Route (at App.js:112)
    in Switch (at App.js:105)
    in div (at App.js:104)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:103)
    in div (at App.js:84)
    in IntlProvider (at App.js:83)
    in ThemeProvider (at App.js:82)
    in JssProvider (at App.js:81)
    in App (at src/index.js:7)
```
```
TypeError: nextCreate is not a function
    at mountMemo (react-dom.development.js:13964)
    at Object.useMemo (react-dom.development.js:14185)
    at useMemo (react.development.js:1525)
    at renderWithHooks (react-dom.development.js:13449)
    at mountIndeterminateComponent (react-dom.development.js:15605)
    at beginWork (react-dom.development.js:16238)
    at performUnitOfWork (react-dom.development.js:20279)
    at workLoop (react-dom.development.js:20320)
    at HTMLUnknownElement.callCallback (react-dom.development.js:147)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:196)
    at invokeGuardedCallback (react-dom.development.js:250)
    at replayUnitOfWork (react-dom.development.js:19503)
    at renderRoot (react-dom.development.js:20433)
    at performWorkOnRoot (react-dom.development.js:21357)
    at performWork (react-dom.development.js:21267)
    at performSyncWork (react-dom.development.js:21241)
    at requestWork (react-dom.development.js:21096)
    at scheduleWork (react-dom.development.js:20909)
    at dispatchAction (react-dom.development.js:14118)
    at index.es.js:260
    at Test2.js:154
```

Where test2 is:
```
import React, { useState, useCallback } from "react";
import ReactDOM from "react-dom";
import CssBaseline from "@material-ui/core/CssBaseline";
import Switch from "@material-ui/core/Switch";
import ArrowDropUpIcon from "@material-ui/icons/ArrowDropUp";
import ArrowDropDownIcon from "@material-ui/icons/ArrowDropDown";
import MoreHorizIcon from "@material-ui/icons/MoreHoriz";
import FolderOpenIcon from "@material-ui/icons/FolderOpen";
import FolderIcon from "@material-ui/icons/Folder";
import SettingsIcon from "@material-ui/icons/Settings";
import DescriptionIcon from "@material-ui/icons/Description";
import InsertDriveFileIcon from "@material-ui/icons/InsertDriveFile";
import AddIcon from "@material-ui/icons/Add";
import DeleteIcon from "@material-ui/icons/Delete";
import { makeStyles, ThemeProvider } from "@material-ui/styles";
import { createMuiTheme } from "@material-ui/core/styles";
import blue from "@material-ui/core/colors/blue";
import pink from "@material-ui/core/colors/pink";
import superagent from "superagent";
import Tree from "material-ui-tree";
import getNodeDataByPath from "material-ui-tree/lib/util";
import { Typography } from "@material-ui/core";

const theme = createMuiTheme({
  palette: {
    primary: blue,
    secondary: {
      light: "#ff79b0",
      main: pink.A200,
      dark: "#c60055",
      contrastText: "#fff"
    }
  }
});

const useStyles = makeStyles({
  container: {
    margin: 20
  },
  icon: {
    fontSize: 20
  },
  node: {
    display: "flex",
    alignContent: "center"
  }
});

const Test2 = () => {
  const classes = useStyles();
  const [state, setState] = useState({
    alignRight: false,
    data: {
      path: "material-ui-tree",
      type: "tree",
      sha: "b3d36479a033ed6296c34fdf689d5cdbcf7a0136",
      url:
        "https://api.github.com/repos/shallinta/material-ui-tree/git/trees/next"
    }
  });

  const renderLabel = useCallback(
    (data, unfoldStatus) => {
      const { path, type } = data;
      let variant = "body1";
      let iconComp = null;
      if (type === "tree") {
        iconComp = unfoldStatus ? <FolderOpenIcon /> : <FolderIcon />;
      }
      if (type === "blob") {
        variant = "body2";
        if (path.startsWith(".") || path.includes("config")) {
          iconComp = <SettingsIcon />;
        } else if (path.endsWith(".js")) {
          iconComp = <DescriptionIcon />;
        } else {
          iconComp = <InsertDriveFileIcon />;
        }
      }
      return (
        iconComp && (
          <Typography variant={variant} className={classes.node}>
            {React.cloneElement(iconComp, { className: classes.icon })}
            {path}
          </Typography>
        )
      );
    },
    [classes]
  );

  const getActionsData = useCallback(
    (data, path, unfoldStatus) => {
      const { type } = data;
      if (type === "tree") {
        if (!unfoldStatus) {
          return null;
        }
        return {
          icon: <AddIcon className={classes.icon} />,
          label: "new",
          hint: "Insert file",
          onClick: () => {
            const treeData = Object.assign({}, state.data);
            const nodeData = getNodeDataByPath(treeData, path, "tree");
            if (
              !Reflect.has(nodeData, "tree") ||
              !Reflect.has(nodeData.tree, "length")
            ) {
              nodeData.tree = [];
            }
            nodeData.tree.push({
              path: "new file",
              type: "blob",
              sha: Math.random()
            });
            setState({ ...state, data: treeData });
          }
        };
      }
      return [
        {
          icon: <DeleteIcon color="secondary" className={classes.icon} />,
          hint: "Delete file",
          onClick: () => {
            const treeData = Object.assign({}, state.data);
            const parentData = getNodeDataByPath(
              treeData,
              path.slice(0, path.length - 1),
              "tree"
            );
            const lastIndex = path[path.length - 1];
            parentData.tree.splice(lastIndex, 1);
            setState({ ...state, data: treeData });
          }
        }
      ];
    },
    [classes, state, setState]
  );

  const requestChildrenData = useCallback(
    (data, path, toggleFoldStatus) => {
      const { url, type } = data;
      if (type === "tree") {
        superagent.get(url).then(({ body: res }) => {
          if (res && res.tree) {
            const treeData = Object.assign({}, state.data);
            getNodeDataByPath(treeData, path, "tree").tree = res.tree;
            setState({
              ...state,
              data: treeData
            });
            toggleFoldStatus();
          } else {
            toggleFoldStatus();
          }
        });
      } else {
        toggleFoldStatus();
      }
    },
    [state, setState]
  );

  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Switch
        checked={state.alignRight}
        onChange={() => setState({ ...state, alignRight: !state.alignRight })}
      />
      Tree Action Buttons Align Right
      <Tree
        className={classes.container}
        title="Material UI Tree"
        data={state.data}
        labelKey="path"
        valueKey="sha"
        childrenKey="tree"
        foldIcon={<ArrowDropDownIcon />}
        unfoldIcon={<ArrowDropUpIcon />}
        loadMoreIcon={<MoreHorizIcon />}
        renderLabel={renderLabel}
        renderLoadMoreText={(page, pageSize, total) =>
          `Loaded: ${(page + 1) *
            pageSize} / Total: ${total}. Click here to load more...`
        }
        pageSize={10}
        actionsAlignRight={state.alignRight}
        getActionsData={getActionsData}
        requestChildrenData={requestChildrenData}
      />
    </ThemeProvider>
  );
};

export default Test2;

```

**Comment by shallinta** [comment]
When I don't do `terser()` in rollup.config, it works fine. I haven't found out what was the matter yet

**Comment by KamalAman** [comment]
I am running into the same issue. 

If I copy the `/src` folder directly master on github and swap my code from using the npm package to the source it works just fine. 

This is definitely an issue with the build.

**Comment by Hawkline451** [comment]
I solve the problem passing the `options` parameter to `terser()` in the rollup.config file
`options =
{
    keep_fnames: true,
}`
`terser(options)`

I m not sure where exactly is the problem but this works

**Comment by nuzz78** [comment]
I tried building a custom version of material-ui-tree, without terser, and with terser options specified above. Neither worked for me. Still getting the above error. Really need a fix to this, as I'm now at a point where I'll have to use a different tree, or write my own.....

**Comment by shallinta** [comment]
> I solve the problem passing the `options` parameter to `terser()` in the rollup.config file
> `options = { keep_fnames: true, }`
> `terser(options)`
> 
> I m not sure where exactly is the problem but this works

This really works if set `keep_fnames` true in terser options though increases size of product.
I will do this first util I have a better solution.
And if anyone could tell the reason please reply this issue. Will really appreciate that!

**Comment by shallinta** [comment]
@nuzz78  What if you try version 2.1.1?

**Comment by nuzz78** [comment]
2.1.1 has fixed it for me. Thanks for that
